version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./start-server.sh
    ports:
      - 5000:5000
    env_file: .env
    volumes:
      - type: bind
        source: ./
        target: /app
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./start-worker.sh
    env_file: .env
    volumes:
      - type: bind
        source: ./output
        target: /app/output
    depends_on:
      - redis
      - db

  db:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379" # Expose Redis on port 6379
